name: tflite_detector
description: "TensorFlow MobileNet v1 example"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image_picker:
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/labels.txt